# Cache: 10 MB shared memory, max 1 GB on disk
server {
    listen 80;
    server_name test-app;

    root /usr/share/nginx/html;
    index index.html;
    # Przykład: load balancing na dwie instancje

    location /api/stats {
        proxy_pass http://instance-backend-service/stats;
    }

    location /api/ {
        proxy_pass http://instance-backend-service/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
