apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployment
    spec:
      containers:
      - name: {{ .Release.Name }}-deployment
        image: "ghcr.io/mikolka9144/net-app/instance-backend:master"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secret
        securityContext:
          runAsUser: 100 # "backend" user in the image
          runAsGroup: 101 # "backend" group in the image
        ports:
        - containerPort: {{ .Values.service.port }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            ephemeral-storage: 1Gi
          requests:
            cpu: 500m
            ephemeral-storage: 256Mi
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 10
      initContainers:
      - name: init-example
        image: registry-1.docker.io/bitnami/postgresql:latest
        command: ['sh', '-c', " PGPASSWORD=\"${POSTGRES_PASSWORD}\" psql -h \"${POSTGRES_HOST}\" -p \"${POSTGRES_PORT:-5432}\" -U \"${POSTGRES_USER}\" -d \"${POSTGRES_DATABASE}\" -v ON_ERROR_STOP=1 -c \"${SQL_INIT_COMMAND}\""]
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secret

