---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.sealed.secret.encryptedData }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Release.Name }}-secret
      namespace: {{ .Values.namespace }}
    type: Opaque
