global:
  namespaceOverride: "cloud-prod"
primary:
  persistence:
    enabled: true
    storageClass: standard
    size: 512Mi
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 512m