apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployment
    spec:
      containers:
        - name: {{ .Release.Name }}-deployment
          image: "ghcr.io/mikolka9144/net-app/instance-frontend:master"
          imagePullPolicy: Always
          ports:
          - containerPort: {{ .Values.ingress_frontendPort }}
          securityContext:
            runAsUser: 101 # "nginx" user in the image
            runAsGroup: 101 # "nginx" group in the image
          volumeMounts:
            - name: ssl-certificates
              mountPath: /etc/nginx/ssl
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ingress_frontendPort }}
              scheme: {{ .Values.ingress_scheme }}
            initialDelaySeconds: 10
            periodSeconds: 45
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ingress_frontendPort }}
              scheme: {{ .Values.ingress_scheme }}
            periodSeconds: 45
          resources:
            limits:
              ephemeral-storage: 1Gi
              memory: 780Mi
            requests:
              cpu: 500m
              ephemeral-storage: 256Mi
              memory: 256Mi
      volumes:
        - name: ssl-certificates
          secret:
            secretName: tls-frontend
          