apiVersion: v1
kind: Secret
metadata:
  name: tls-frontend
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.sealed.tlssecret.encryptedData }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
