namespace: cloud-prod
secrets:
  data:
    POSTGRES_PASSWORD: cGFzc3dvcmQ=
    REDIS_PASSWORD: ZGkzYzRPV1NFVw==
configMap:
  data:
    PORT: 80
    POSTGRES_DATABASE: app-data
    POSTGRES_USER: admin
    POSTGRES_HOST: postgresql
    REDIS_URL: redis://instance-redis-headless:6379