replicaCount: 1
service:
  type: ClusterIP
  port: 8080
secrets:
  data:
    POSTGRES_PASSWORD: cGFzc3dvcmQ=
configMap:
  data:
    POSTGRES_DATABASE: app-data
    POSTGRES_USER: admin
    POSTGRES_HOST: postgresql
    REDIS_URL: redis://instance-redis-master:6379