replicaCount: 1
service:
  type: ClusterIP
  port: 8080
secrets:
  data:
    POSTGRES_PASSWORD: cG9zdGdyZXMtcGFzc3dvcmQK
configMap:
  data:
    POSTGRES_DATABASE: app-data
    POSTGRES_USER: instance-app
    POSTGRES_HOST: postgresql