ingressClass: nginx
ingress_frontendPort: 443
ingress_scheme: HTTPS
service:
  type: ClusterIP
  port: 80
primary:
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 512m
